os: windows
language: go

go:
  - 1.16.x

script:
  - choco upgrade mingw cmake -y --no-progress
  - choco version all
  - cd mdbx/dist
  - cp C:/WINDOWS/SYSTEM32/ntdll.dll .
  - cmake -G "MinGW Makefiles" . -D MDBX_BUILD_SHARED_LIBRARY:BOOL=ON -D MDBX_WITHOUT_MSVC_CRT:BOOOL=OFF -D CMAKE_C_FLAGS:STRING="-Wno-unused-variable -Wno-unused-parameter -Wno-unused-function" -D CMAKE_CXX_FLAGS:STRING="-Wno-unused-variable -Wno-unused-parameter -Wno-unused-function"
  - cmake --build .
  - cd ./..
  - go build .
  - go test -v .
#  - cp libmdbx.dll C:/WINDOWS/SYSTEM32/
#  - cmake -G "MinGW Makefiles" . -D MDBX_BUILD_SHARED_LIBRARY:BOOL=ON -D MDBX_WITHOUT_MSVC_CRT:BOOOL=OFF -D CMAKE_C_FLAGS:STRING="-Wno-unused-variable -Wno-unused-parameter -Wno-unused-function" -D CMAKE_CXX_FLAGS:STRING="-Wno-unused-variable -Wno-unused-parameter -Wno-unused-function"

