os: windows
language: go

go:
  - 1.16.x

script:
  - choco upgrade mingw cmake git -y --no-progress
  - choco version all
  - cd mdbx/dist
  - cmake -G "MinGW Makefiles" . -D MDBX_BUILD_SHARED_LIBRARY:BOOL=ON -D MDBX_WITHOUT_MSVC_CRT:BOOOL=OFF -D CMAKE_C_FLAGS:STRING="-Wno-unused-variable -Wno-unused-parameter -Wno-unused-function" -D CMAKE_CXX_FLAGS:STRING="-Wno-unused-variable -Wno-unused-parameter -Wno-unused-function"
  - cmake --build .
  - cp libmdbx.dll C:/WINDOWS/SYSTEM32/
  - ls .
  - cd ./..
  - go build .
  - go test -a -v -work .
#  - pwd && cmake -G "MinGW Makefiles" . -D CMAKE_MAKE_PROGRAM:PATH=C:/ProgramData/chocolatey/bin/make.exe -D MDBX_BUILD_SHARED_LIBRARY:BOOL=ON -D CMAKE_C_FLAGS:STRING="-Wno-unused-variable -Wno-unused-parameter -Wno-unused-function" -D CMAKE_CXX_FLAGS:STRING="-Wno-unused-variable -Wno-unused-parameter -Wno-unused-function"

