name: Test
on: [ push ]
jobs:

  test:
    strategy:
      matrix:
        os: [ windows-latest ] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.16' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: checkout submodule
        run: |
          git submodule init
          git submodule update
          cd libmdbx && git checkout devel

      #      - name: Add msbuild to PATH
      #        uses: microsoft/setup-msbuild@v1.0.2

      - name: build mdbx
        run: |
          cmake --version
          cd libmdbx
          mkdir build
          cd build
          cmake -DMDBX_WITHOUT_MSVC_CRT:BOOL=ON ..
          cmake --build . --target mdbx-static
          ls
          cd ../..
          echo $LDFLAGS
          make win2


      #          docker run --rm dockcross/windows-static-x64-posix > ./dockcross
      #          chmod +x ./dockcross
      #          ./dockcross cmake -B./build -H./libmdbx
      #          ./dockcross cmake --build ./build --target mdbx-static
      #
      #          cp libmdbx/mdbx.h mdbx/
      #          cmake -DBUILD_SHARED:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DMDBX_WITHOUT_MSVC_CRT:BOOL=ON .

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: |
          ls mdbx/
          make win2

#https://github.com/golang/go/issues/20982
