name: Test
on: [ push ]
jobs:

  test:
    strategy:
      matrix:
        os: [ windows-latest ] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.16' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: checkout submodule
        run: |
          git submodule init
          git submodule update
          cd libmdbx && git checkout devel && cd .. && cp 2.patch libmdbx && cd libmdbx && git apply 2.patch

#      - name: Add msbuild to PATH
#        uses: microsoft/setup-msbuild@v1.0.2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: make win

#https://github.com/golang/go/issues/20982
