name: Test
on: [push]
jobs:

#  lint:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-go@v2
#        with:
#          go-version: 1.14.x
#
#      - name: Install dependencies
#        run: sudo apt update && sudo apt install make libc-dev gcc g++
#
#      - name: lint
#        uses: golangci/golangci-lint-action@v1
#        with:
#          version: v1.29
#          only-new-issues: true

  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15] # list of os: https://github.com/actions/virtual-environments
#        os: [ubuntu-20.04, macos-10.15, windows-latest] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.15', '1.13' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Add Msys64 to PATH # see https://github.com/actions/virtual-environments/issues/1613 and https://github.com/actions/virtual-environments/pull/1648
        if: matrix.os == 'windows-latest'
        run: echo "::add-path::/c/msys64/mingw64/bin:/c/msys64/usr/bin"
        shell: bash

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-${{ matrix.os }}-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}

      - name: Test
        run: make test

      - name: Race
        run: make race
