name: Test
on: [ push ]
jobs:

  test:
    strategy:
      matrix:
        os: [ windows-latest ] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.16' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-${{ matrix.os }}-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}

      - name: Test1
        run: cd libmdbx && ls && cmake . && cmake --build . -DCMAKE_BUILD_TYPE=Release -DMDBX_INSTALL_STATIC=1  && cd .. && ls && ls libmdbx && ls libmdbx/Debug

      - name: Test
        run: make win

#https://github.com/golang/go/issues/20982
