name: Test
on: [ push ]
jobs:

  test:
    strategy:
      matrix:
        os: [ windows-latest ] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.16' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: checkout submodule
        run: |
          git submodule init
          git submodule update
          cd libmdbx && git checkout devel

      #      - name: Add msbuild to PATH
      #        uses: microsoft/setup-msbuild@v1.0.2

      - name: build mdbx
        run: |
          cmake --version
          cd libmdbx
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..
          cmake --build . --target mdbx-static
          ls
          ar -xv ./libmdbx-static.a
          ls
          echo "alex"
          pwd
          cd ..
          pwd
          cp libmdbx/build/alloy.c.obj mdbx/
          cp libmdbx/build/alloy.c.obj .
          pwd
          cp libmdbx/mdbx.h mdbx/
          ls mdbx/
          cp C:\WINDOWS\SYSTEM32\ntdll.dll mdbx/
          cp C:\WINDOWS\SYSTEM32\ntdll.dll .

      #          cmake -DBUILD_SHARED:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DMDBX_WITHOUT_MSVC_CRT:BOOL=ON .


      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: make win2

#https://github.com/golang/go/issues/20982
