name: Test
on: [ push ]
jobs:

  test:
    strategy:
      matrix:
        os: [ windows-latest ] # list of os: https://github.com/actions/virtual-environments
        go: [ '1.16' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      #      - uses: ilammy/msvc-dev-cmd@v1

      - name: upgr
        run: |
          choco version all
          choco upgrade mingw cmake git -y --no-progress
      #          choco install visualstudio2019buildtools

      - name: checkout submodule
        run: |
          git submodule update --force --recursive --init --remote
          cd libmdbx
          ls .
          mkdir build && cd build
          ls .
          cmake -DMDBX_WITHOUT_MSVC_CRT:BOOL=ON ..
          cmake --build . --target mdbx
          ls .
          echo '#define MDBX_WITHOUT_MSVC_CRT 1' >> config.h
          cat config.h
          cd ../../
          cp libmdbx/build/config.h mdbx/

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      #      - name: Add msbuild to PATH
      #        uses: microsoft/setup-msbuild@v1.0.2

      #      - name: mvsc
      #        shell: cmd
      #        run: |
      #          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      #          set PATH="C:\P\grep;%PATH%"
      #          set CC=cl.exe
      #          set CXX=cl.exe

      - name: mingw
        run: |
          cmake --version
          SET C
          cp ./mdbx/dist/mdbx.h ./mdbx
          cp ./mdbx/dist/mdbx.c ./mdbx
          go env
          make win3

      #          cmake -G "MinGW Makefiles" -DMDBX_WITHOUT_MSVC_CRT:BOOL=ON ..
      #          cmake --build . --target mdbx
      #          ls
      #          ls Debug
      #          cp Debug/mdbx.lib .
      #           cmake -G "MinGW Makefiles" ..
      #  -DMDBX_WITHOUT_MSVC_CRT:BOOL=ON
      #          docker run --rm dockcross/windows-static-x64-posix > ./dockcross
      #          ./dockcross cmake -B./build -H./libmdbx
      #          ./dockcross cmake --build ./build --target mdbx-static
      #x
      #          cp libmdbx/mdbx.h mdbx/
      #          cmake -DBUILD_SHARED:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DMDBX_WITHOUT_MSVC_CRT:BOOL=ON .


#https://github.com/golang/go/issues/20982
